# Generated by Django 5.2.1 on 2025-05-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de WhatsApp', max_length=15, null=True),
        ),
    ]
