# Generated by Django 5.2.1 on 2025-05-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='user',
        ),
        migrations.AddField(
            model_name='teammember',
            name='name',
            field=models.CharField(default='Membro', max_length=100),
            preserve_default=False,
        ),
    ]
