# Generated by Django 5.2.1 on 2025-05-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_teammember_email_alter_teammember_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutyschedule',
            name='coffees_served',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de cafés servidos neste turno'),
        ),
        migrations.AddField(
            model_name='dutyschedule',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações sobre esta escala', null=True),
        ),
    ]