# Generated by Django 5.2.1 on 2025-07-14 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dutyschedule_coffees_served_dutyschedule_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='cleaning_preference',
            field=models.CharField(choices=[('auto', 'Automático (30min antes da saída)'), ('early', 'Preferência por horário mais cedo'), ('late', 'Preferência por horário mais tarde')], default='auto', help_text='Como calcular o horário de limpeza', max_length=20),
        ),
        migrations.AddField(
            model_name='teammember',
            name='exit_time',
            field=models.TimeField(default=datetime.time(18, 0), help_text='Horário de saída da empresa (usado para calcular horário de limpeza)'),
        ),
    ]
